export const WEB_SERVER_DISCONNECTED = 'system/WEB_SERVER_DISCONNECTED';
export const WEB_SERVER_CONNECTED = 'system/WEB_SERVER_CONNECTED';

export const MONGODB_DISCONNECTED = 'system/MONGODB_DISCONNECTED';
export const MONGODB_CONNECTED = 'system/MONGODB_CONNECTED';

export const WEB_SOCKET_DISCONNECTED = 'system/WEB_SOCKET_DISCONNECTED';
export const WEB_SOCKET_CONNECTED = 'system/WEB_SOCKET_CONNECTED';

export const GRAPH_QL_SERVER_DISCONNECTED =
  'system/GRAPH_QL_SERVER_DISCONNECTED';
export const GRAPH_QL_SERVER_CONNECTED = 'system/GRAPH_QL_SERVER_CONNECTED';
